<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <!-- Release Settings -->
    <PropertyGroup>
        <Description>The Roslyn Engine for the YScriptEngine project.</Description>
        <PackageTags>YScriptEngine;Scripting;Roslyn</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\YScriptEngine.Abstractions\YScriptEngine.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0" />
      <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="5.6.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    </ItemGroup>

</Project>
