<Project>
    <PropertyGroup>
        <!-- Versioning & Lifecycle -->
        <Version>1.0.0-alpha</Version>
        <Authors>Yes</Authors>
        <Company>Yes's Stuff and Things</Company>

        <!-- Licensing (No extra file needed) -->
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

        <!-- Repository & Strategy -->
        <RepositoryUrl>https://github.com/ysnt-yes/YScriptEngine</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <!-- Build Configurations -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>