<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <!-- Release Settings -->
    <PropertyGroup>
        <Description>The contracts package for the main YScriptEngine project.</Description>
        <PackageTags>YScriptEngine;Scripting</PackageTags>
    </PropertyGroup>

</Project>
