<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <!-- Release Settings -->
    <PropertyGroup>
        <Description>The LSP Abstractions for the YScriptEngine project.</Description>
        <PackageTags>YScriptEngine;Scripting;Lsp</PackageTags>
    </PropertyGroup>

</Project>
